micronaut:
  application:
    name: micronaut-openwhisk-jpa-sample
datasources:
  default:
    name: prod
    url: jdbc:postgresql://baasu.db.elephantsql.com:5432/tcfzblyo
    username: tcfzblyo
    password: FYu40IAxBQJu3osSuCM2oV1d4IksZ3vB
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - 'com.ibm.openwhisk.micronaut.jpa.sample'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
testprop: hellothere
